services:
  eureka:
    image: scarletbobcat/eureka:1.0
    ports:
      - "8761:8761"
    networks:
      - rhythmflow
  users:
    image: scarletbobcat/users:1.0
    ports:
      - "8081:8081"
    networks:
      - rhythmflow
    env_file:
      - ./Users/.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  music:
    image: scarletbobcat/music:1.0
    ports:
      - "9090:9090"
    networks:
      - rhythmflow
    env_file:
      - ./Music/.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  gateway:
    image: scarletbobcat/gateway:1.0
    networks:
      - rhythmflow
    ports:
      - "8080:8080"
    env_file:
      - ./Gateway/.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  frontend:
    image: scarletbobcat/rhythmflow:1.0
    networks:
      - rhythmflow
    ports:
      - "5173:5173"
    # env_file:
    #   - ./Frontend/.env

networks:
  rhythmflow:
