services:
  eureka:
    image: scarletbobcat/eureka:latest
    ports:
      - "8761:8761"
    networks:
      - rhythmflow
  users:
    image: scarletbobcat/users:latest
    ports:
      - "8081:8081"
    networks:
      - rhythmflow
    env_file:
      - path: ./Users/.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  music:
    image: scarletbobcat/music:latest
    ports:
      - "9090:9090"
    networks:
      - rhythmflow
    env_file:
      - path: ./Music/.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  gateway:
    image: scarletbobcat/gateway:latest
    networks:
      - rhythmflow
    ports:
      - "8080:8080"
    env_file:
      - path: ./Gateway/.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  search:
    image: scarletbobcat/search:latest
    networks:
      - rhythmflow
    ports:
      - "7070:7070"
    env_file:
      - path: ./Search/.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  frontend:
    image: scarletbobcat/frontend:latest
    networks:
      - rhythmflow
    ports:
      - "5173:80"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rhythmflow

networks:
  rhythmflow:
