spring:
  application:
    name: users
  profiles:
    active: dev
  datasource:
    url: ${NEON_USERS_DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PWD}
    virtual-host: /

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}
    # The important part - use the service name rather than pod hostname
    hostname: ${spring.application.name}

supabase:
  url: ${SUPABASE_URL}
  serviceRoleKey: ${SUPABASE_SERVICE_ROLE_KEY}

server:
  port: 8081

rabbitmq:
  logging:
    queue: log.queue
