spring:
  application:
    name: Users
  profiles:
    active: dev
  datasource:
    url: ${SUPABASE_SESSION_POOL}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /

server:
  port: 8081
