spring:
  application:
    name: users
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${NEON_USERS_DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PWD}
    virtual-host: /

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}
    # The important part - use the service name rather than pod hostname
    hostname: ${spring.application.name}

# Enable health endpoint
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

supabase:
  url: ${SUPABASE_URL}
  serviceRoleKey: ${SUPABASE_SERVICE_ROLE_KEY}

server:
  port: 8081

rabbitmq:
  logging:
    queue: log.queue
  users:
    queue: users.queue
  music:
    queue: music.queue
  search:
    queue: search.queue

r2:
  endpoint: ${R2_ENDPOINT}
  public-url: ${R2_PUBLIC_URL}
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  bucket-name: ${R2_BUCKET_NAME}

