server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    preferIpAddress: true
    hostname: ${spring.application.name:eureka}
  server:
    enableSelfPreservation: false
    # Lower values help with faster service discovery in Kubernetes
    renewalPercentThreshold: 0.85
    evictionIntervalTimerInMs: 5000
    responseCacheUpdateIntervalMs: 3000
