spring:
  application:
    name: RhythmFlow-Gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**
#          filters:
#            - AuthenticationFilter

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG
