spring:
  application:
    name: RhythmFlow-Gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: users
          uri: lb://USERS
          predicates:
            - Path=/users/**
        - id: music
          uri: lb://MUSIC
          predicates:
              - Path=/music/**

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
