# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     kompose.cmd: kompose -f ../RhythmFlow/docker-compose.yml convert
#     kompose.version: 1.35.0 (HEAD)
#   labels:
#     io.kompose.service: eureka
#   name: eureka
# spec:
#   replicas: 5
#   selector:
#     matchLabels:
#       io.kompose.service: eureka
#   template:
#     metadata:
#       annotations:
#         kompose.cmd: kompose -f ../RhythmFlow/docker-compose.yml convert
#         kompose.version: 1.35.0 (HEAD)
#       labels:
#         io.kompose.service: eureka
#     spec:
#       containers:
#         - image: scarletbobcat/eureka:arm
#           name: eureka
#           ports:
#             - containerPort: 8761
#               protocol: TCP
#       restartPolicy: Always
