apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-cloud-gateway
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spring-cloud-gateway
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spring-cloud-gateway
subjects:
  - kind: ServiceAccount
    name: spring-cloud-gateway
    namespace: default
roleRef:
  kind: ClusterRole
  name: spring-cloud-gateway
  apiGroup: rbac.authorization.k8s.io
