spring:
  application:
    name: Music
  profiles:
    active: dev
  datasource:
    url: ${NEON-DB-URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /

server:
  port: 9090



cloudflare:
  r2:
    bucket-name: ${R2-BUCKET-NAME}
    endpoint: ${R2-ENDPOINT}
    access-key: ${R2-ACCESS-KEY}
    secret-key: ${R2-SECRET-KEY}

