spring:
  application:
    name: music
  profiles:
    active: dev
  datasource:
    url: ${NEON-DB-URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PWD}
    virtual-host: /

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}
    # The important part - use the service name rather than pod hostname
    hostname: ${spring.application.name}

server:
  port: 9090

cloudflare:
  r2:
    bucket-name: ${R2_BUCKET_NAME}
    endpoint: ${R2_ENDPOINT}
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}

rabbitmq:
  logging:
    queue: log.queue
  users:
    queue: user.queue