name: Build and Push Docker Images
on:
  workflow_dispatch:
  workflow_call:

jobs:
  DetectChanges:
    uses: ./.github/workflows/detect-changes.yml

  Build-And-Push:
    runs-on: ubuntu-latest
    if: ${{ needs.DetectChanges.outputs.matrix != '[]'}}
    needs: DetectChanges
    strategy:
      matrix:
        service: ${{ fromJson(needs.DetectChanges.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check if username is set
        run: |
          if [ -z "$MY_SECRET" ]; then
            echo "MY_SECRET is empty"
          else
            echo "MY_SECRET is set"
          fi
        env:
          MY_SECRET: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Check if token is set
        run: |
          if [ -z "$MY_SECRET" ]; then
            echo "MY_SECRET is empty"
          else
            echo "MY_SECRET is set"
          fi
        env:
          MY_SECRET: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: test
      #   run: |
      #     echo ${{ secrets.DOCKERHUB_USERNAME }}
      #     echo ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create ENV file for Frontend
        if: ${{ matrix.service == 'frontend' }}
        run: |
          echo "${{ secrets.FRONTEND_ENV }}" > ./${{ matrix.service }}/.env

      - name: Build and push image for ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
