name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  DetectChanges:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      gateway: ${{ steps.filter.outputs.gateway }}
      eureka: ${{ steps.filter.outputs.eureka }}
      users: ${{ steps.filter.outputs.users }}
      music: ${{ steps.filter.outputs.music }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect folder changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'Frontend/**'
            gateway:
              - 'Gateway/**'
            eureka:
              - 'EurekaServer/**'
            users:
              - 'Users/**'
            music:
              - 'Music/**'

  Frontend:
    needs: DetectChanges
    if: needs.DetectChanges.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        working-directory: ./Frontend
        run: npm install

      - name: Build
        working-directory: ./Frontend
        run: npm run build

      - name: SonarQube scan
        uses: sonarcloud-scan-action
        with:
          projectBaseDir: ./Frontend
          args: >
            -Dsonar.projectKey=rhythmflow_frontend
            -Dsonar.organization=scarletbobcat
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.inclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Gateway:
    needs: DetectChanges
    if: needs.DetectChanges.outputs.gateway == 'true'
    uses: scarletbobcat/rhythmflow/.github/workflows/java.yml@main
    with:
      directory: ./Gateway
      SONAR_PROJECT_KEY: rhythmflow_gateway
    secrets: inherit

  Eureka:
    needs: DetectChanges
    if: needs.DetectChanges.outputs.eureka == 'true'
    uses: scarletbobcat/rhythmflow/.github/workflows/java.yml@main
    with:
      directory: ./EurekaServer
      SONAR_PROJECT_KEY: rhythmflow_eureka
    secrets: inherit

  Users:
    needs: DetectChanges
    if: needs.DetectChanges.outputs.users == 'true'
    uses: scarletbobcat/rhythmflow/.github/workflows/java.yml@main
    with:
      directory: ./Users
      SONAR_PROJECT_KEY: rhythmflow_users
    secrets: inherit

  Music:
    needs: DetectChanges
    if: needs.DetectChanges.outputs.music == 'true'
    uses: scarletbobcat/rhythmflow/.github/workflows/java.yml@main
    with:
      directory: ./Music
      SONAR_PROJECT_KEY: rhythmflow_music
    secrets: inherit
