name: CI

on:
  push:
    branches: [master, main, dev]
  pull_request:
    branches: [master, main, dev]

jobs:
  DetectChanges:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      gateway: ${{ steps.filter.outputs.gateway }}
      eureka: ${{ steps.filter.outputs.eureka }}
      users: ${{ steps.filter.outputs.users }}
      music: ${{ steps.filter.outputs.music }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect folder changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'Frontend/**'
            gateway:
              - 'Gateway/**'
            eureka:
              - 'EurekaServer/**'
            users:
              - 'Users/**'
            music:
              - 'Music/**'

  Frontend:
    needs: DetectChanges
    if: needs.DetectChanges.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        working-directory: ./Frontend
        run: npm install

      - name: Build
        working-directory: ./Frontend
        run: npm run build

  Gateway:
    needs: DetectChanges
    if: needs.DetectChanges.outputs.gateway == 'true'
    uses: scarletbobcat/rhythmflow/.github/workflows/java.yml@main
    with:
      directory: ./Gateway
    secrets: inherit

  Eureka:
    needs: DetectChanges
    if: needs.DetectChanges.outputs.eureka == 'true'
    uses: scarletbobcat/rhythmflow/.github/workflows/java.yml@main
    with:
      directory: ./EurekaServer
    secrets: inherit

  Users:
    needs: DetectChanges
    if: needs.DetectChanges.outputs.users == 'true'
    uses: scarletbobcat/rhythmflow/.github/workflows/java.yml@main
    with:
      directory: ./Users
    secrets: inherit

  Music:
    needs: DetectChanges
    if: needs.DetectChanges.outputs.music == 'true'
    uses: scarletbobcat/rhythmflow/.github/workflows/java.yml@main
    with:
      directory: ./Music
    secrets: inherit

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Sonar project key
        id: sonar-key
        run: |
          # Extract the base name from directory path (remove ./ if present)
          DIR_NAME=$(basename "test" | sed 's/^\.\///')

          # Convert to uppercase for consistency
          DIR_NAME_UPPER=$(echo "$DIR_NAME" | tr '[:lower:]' '[:upper:]')

          # Set the project key (base + directory name)
          echo "PROJECT_KEY=SONAR_PROJECT_KEY_${DIR_NAME_UPPER}" >> $GITHUB_OUTPUT

          echo "Using project key: SONAR_PROJECT_KEY_${DIR_NAME_UPPER} for directory: $DIR_NAME"

      - name: Use output
        run: echo "Project key is ${{ steps.sonar-key.outputs.project_key }}"
        # env:
        #   SONAR_PROJECT_KEY: ${{ steps.sonar-key.outputs.project_key }}
