name: Deploy
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - main
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:

jobs:
  DetectChanges:
    uses: ./.github/workflows/detect-changes.yml

  Build-And-Push:
    uses: ./.github/workflows/build-and-push.yml

  Deploy:
    needs:
      - DetectChanges
      - Build-And-Push
    strategy:
      matrix:
        service: ${{ fromJson(needs.DetectChanges.outputs.matrix) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group RhythmFlow --name RhythmFlow --overwrite-existing

      - name: Create Secret Name
        run: |
          SECRET_NAME="$(echo "${{ matrix.service }}" | tr '[:lower:]' '[:upper:]')_ENV"
          echo "SECRET_NAME=${SECRET_NAME}" >> $GITHUB_ENV
          echo "HAS_SECRET=${{ contains(toJson(secrets), env.SECRET_NAME) }}" >> $GITHUB_ENV

      - name: Create ENV file
        if: ${{ env.HAS_SECRET == 'true' }}
        run: |
          echo "${{ secrets[env.SECRET_NAME] }}" > ./${{ matrix.service }}/.env
          kubectl create configmap ${{ matrix.service }}-env --from-env-file=./${{ matrix.service }}/.env --dry-run=client -o yaml | kubectl apply -f -

      # - name: Deploy NGINX Ingress Controller
      #   run: |
      #     kubectl apply -f k8s/api-ingress.yaml
      #     kubectl apply -f k8s/frontend-ingress.yaml
      #     kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/

      - name: Restart Deployment
        run: |
          kubectl rollout restart deployment ${{ matrix.service }}
