name: Dynamic Matrix from Path Filters

on:
  workflow_call:
    outputs:
      matrix:
        description: "The matrix of changed components"
        value: ${{ jobs.changes.outputs.matrix }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          base: ${{ github.ref || 'main' }}
          ref: ${{ github.head_ref || github.ref }}
          filters: |
            frontend:
              - 'frontend/**'
            eureka:
              - 'eureka/**'
            music:
              - 'music/**'
            search:
              - 'search/**'
            gateway:
              - 'gateway/**'
            users:
              - 'users/**'

      - name: Set matrix
        id: set-matrix
        run: |
          matrix=$(jq -n -c '
            [
              "frontend",
              "eureka",
              "music",
              "search",
              "gateway",
              "users"
            ] | map(select(. != null))
          ')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          echo "$matrix"

#("frontend" | select("${{ steps.changes.outputs.frontend }}" == "true")),
