on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
        default: "."
      sonar_project_key:
        required: false
        type: string
        default: "rhythmflow"
jobs:
  ProjectKey:
    runs-on: ubuntu-latest

  SonarCloud:
    runs-on: ubuntu-latest
    outputs:
      sonar_project_key: ${{ steps.projectKey.outputs.projectKey }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Build
        working-directory: ${{ inputs.directory }}
        run: mvn clean package

      - name: Run tests
        working-directory: ${{ inputs.directory }}
        run: mvn test

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Determine Sonar project key
        id: sonar-key
        run: |
          # Extract the base name from directory path (remove ./ if present)
          DIR_NAME=$(basename "${{ inputs.directory }}" | sed 's/^\.\///')

          # Convert to uppercase for consistency
          DIR_NAME_UPPER=$(echo "$DIR_NAME" | tr '[:lower:]' '[:upper:]')

          # Set the project key (base + directory name)
          echo "PROJECT_KEY=SONAR_PROJECT_KEY_${DIR_NAME_UPPER}" >> $GITHUB_OUTPUT

          echo "Using project key: SONAR_PROJECT_KEY_${DIR_NAME_UPPER} for directory: $DIR_NAME"

      - name: SonarCloud Scan (Music)
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ${{ inputs.directory }}
          args: >
            -Dsonar.projectKey=${{ steps.sonar-key.outputs.projectKey }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.java.binaries=target/classes
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
