name: Playwright E2E Tests

on:
  pull_request:
    branches: [dev]

jobs:
  DetectChanges:
    uses: ./.github/workflows/detect-changes.yml

  Build-And-Push:
    uses: ./.github/workflows/build-and-push.yml

  e2e:
    runs-on: ubuntu-latest
    needs: Build-And-Push
    env:
      frontend-dir: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create env files
        run: |
          echo "${{ secrets.USERS_ENV }}" > ./users/.env
          echo "${{ secrets.MUSIC_ENV }}" > ./music/.env
          echo "${{ secrets.GATEWAY_ENV }}" > ./gateway/.env
          echo "${{ secrets.SEARCH_ENV }}" > ./search/.env
          echo "${{ secrets.LOGGING_ENV }}" > ./logging/.env
          echo "${{ secrets.FRONTEND_ENV }}" > ./frontend/.env

      - name: Build and start services
        run: docker-compose up -d

      - name: Install pnpm
        working-directory: ./${{ env.frontend-dir}}
        run: npm install -g pnpm

      - name: Install dependencies with pnpm
        working-directory: ./${{ env.frontend-dir}}
        run: pnpm install

      - name: Install Playwright Browsers
        working-directory: ./${{ env.frontend-dir}}
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./${{ env.frontend-dir}}
        run: pnpm run test:e2e

      - name: Upload HTML report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ${{ env.frontend-dir }}/playwright-report
